#/bin/bash /Applications/DYMO.WebApi.Mac.Host.app/Contents/Resources/InstallCertificates.sh

echo '🚀 CRED BOARD VM SETUP - THE WHOLE NINE YARDS'
echo '=============================================='
echo ''
echo '🎯 OBJECTIVE: Run CredBoard GUI in Windows ARM64 VM on Apple Silicon'
echo ''

# Check if UTM is installed
if ! command -v utmctl &> /dev/null && ! command -v utm &> /dev/null; then
    echo '📦 STEP 1: Install UTM'
    echo '====================='
    echo ''
    echo 'Run this command:'
    echo 'brew install utm'
    echo ''
    echo 'OR download from: https://mac.getutm.app/'
    echo ''
    read -p 'Press Enter after installing UTM...'
fi

echo ''
echo '📥 STEP 2: Download Windows ARM64 ISO'
echo '====================================='
echo ''
echo '🔗 OPEN THIS URL in your browser:'
echo 'https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewARM64'
echo ''
echo '📋 Download: Windows 11 ARM64 ISO (about 5GB)'
echo ''
read -p 'Press Enter after downloading the ISO...'

echo ''
echo '🖥️  STEP 3: Create VM in UTM'
echo '==========================='
echo ''
echo 'INSTRUCTIONS:'
echo '1. Open UTM application'
echo '2. Click "+" button → "Create a New Virtual Machine"'
echo '3. Select "Windows" → "Windows 11 (ARM64)"'
echo '4. Configure:'
echo '   - RAM: 4GB'
echo '   - CPU: 2 cores'
echo '   - Storage: 64GB'
echo '   - Enable graphics acceleration'
echo '5. Mount the downloaded Windows ARM64 ISO'
echo '6. Save VM configuration'
echo ''
read -p 'Press Enter after creating VM in UTM...'

echo ''
echo '⏳ STEP 4: Install Windows (15-30 minutes)'
echo '=========================================='
echo ''
echo 'INSTRUCTIONS:'
echo '1. Start the VM in UTM'
echo '2. Follow Windows installation wizard'
echo '3. Choose language and region'
echo '4. Accept license terms'
echo '5. Choose "Custom" installation'
echo '6. Select the virtual disk'
echo '7. Wait for installation to complete'
echo '8. Set up user account and password'
echo ''
read -p 'Press Enter after Windows installation completes...'

echo ''
echo '🔧 STEP 5: Setup CredBoard Environment'
echo '======================================'
echo ''
echo 'IN WINDOWS VM POWERSHELL, run these commands:'
echo ''
echo '# Install .NET Runtime'
echo 'winget install Microsoft.DotNet.Runtime.8'
echo ''
echo '# Create test directory'
echo 'New-Item -ItemType Directory -Path "C:\CredBoard-Test" -Force'
echo ''
read -p 'Press Enter after running the PowerShell commands...'

echo ''
echo '📤 STEP 6: Transfer CredBoard to VM'
echo '==================================='
echo ''
echo 'From your Mac terminal (replace VM-IP with actual VM IP):'
echo 'scp ~/Sync/CredBoard.exe user@VM-IP:C:/CredBoard-Test/'
echo ''
read -p 'Press Enter after transferring the file...'

echo ''
echo '🎯 STEP 7: TEST CREDBOARD GUI'
echo '============================'
echo ''
echo 'IN WINDOWS VM:'
echo '1. Open File Explorer'
echo '2. Navigate to C:\CredBoard-Test'
echo '3. Double-click CredBoard.exe'
echo ''
echo 'WHAT YOU SHOULD SEE:'
echo '✅ Windows Forms GUI launches'
echo '✅ Login screen with password field'
echo '✅ Master password authentication'
echo '✅ Dashboard with client management'
echo '✅ Full working Windows application'
echo ''
read -p 'Press Enter to start testing...'

echo ''
echo '📸 STEP 8: TAKE SCREENSHOTS'
echo '==========================='
echo ''
echo 'SCREENSHOTS TO TAKE:'
echo '1. Login Screen - Win + Shift + S'
echo '2. Dashboard - Win + Shift + S'  
echo '3. Add Client Modal - Win + Shift + S'
echo '4. Client List - Win + Shift + S'
echo '5. Edit Credentials - Win + Shift + S'
echo ''
echo 'SAVE AS:'
echo 'login-screen.png'
echo 'dashboard.png'
echo 'add-client-modal.png'
echo 'client-list.png'
echo 'edit-credentials.png'
echo ''
read -p 'Press Enter after taking screenshots...'

echo ''
echo '📋 STEP 9: RUN AUTOMATED TESTS'
echo '=============================='
echo ''
echo 'IN WINDOWS VM POWERSHELL:'
echo '& "C:\CredBoard-Test	est-gui.ps1"'
echo ''
read -p 'Press Enter after running automated tests...'

echo ''
echo '🎉 SETUP COMPLETE!'
echo '================='
echo ''
echo '📊 SUMMARY:'
echo '✅ UTM VM created and configured'
echo '✅ Windows ARM64 installed'
echo '✅ .NET Runtime installed'
echo '✅ CredBoard.exe transferred'
echo '✅ GUI application tested'
echo '✅ Screenshots captured'
echo '✅ Automated tests run'
echo ''
echo '📁 FILES CREATED:'
echo 'C:\CredBoard-Test\CredBoard.exe'
echo 'C:\CredBoard-Test\*.png (screenshots)'
echo ''
echo '🎯 RESULT: CredBoard GUI fully tested in Windows ARM64 VM!'
echo ''
echo '💡 Next: Share screenshots and feedback on the GUI experience!'


